"""B-roll cut from the clip's own words, generated locally.

No stock library and no fetching: the shots are generated by the same
local models the Generation Studio uses, from subjects taken out of the
transcript. That keeps the "nothing leaves this machine" rule intact and
means the B-roll is about what is actually being said.

The judgement that matters here is WHERE b-roll goes. Cutting away during
a sentence buries the speaker mid-thought, and cutting away from a face
that is talking is exactly what the tracking stage works to avoid. So
inserts are placed in the gaps BETWEEN sentences, never over a hook, and
capped — b-roll that never returns to the speaker is a slideshow.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from clipforge.log import get_logger

log = get_logger(__name__)

#: Never cut away inside the opening. The hook is the whole reason a
#: viewer stays; covering it with scenery is how a good clip dies.
HOOK_PROTECT_S = 3.0

#: An insert shorter than this reads as a glitch rather than an edit.
MIN_INSERT_S = 1.2

#: Fraction of a clip that may be b-roll before it stops being a talking
#: piece and becomes a slideshow.
MAX_COVERAGE = 0.35


@dataclass(frozen=True)
class BRollCue:
    """One planned insert: when to cut away, for how long, and about what."""

    start_s: float
    duration_s: float
    subject: str
    prompt: str

    @property
    def end_s(self) -> float:
        return self.start_s + self.duration_s


def plan_broll(segments, *, clip_duration_s: float, style: str = "",
               max_cues: int = 3, min_gap_s: float = 0.35,
               insert_s: float = 2.0) -> list[BRollCue]:
    """Where b-roll should go, and what each insert should show.

    ``segments`` are transcript segments with .start/.end/.text. Inserts
    land in the pauses between sentences: that is where an editor cuts,
    because the sentence has landed and the next has not started.
    """
    from clipforge.export_pack import keywords

    segs = [s for s in (segments or [])
            if getattr(s, "start", None) is not None]
    cues: list[BRollCue] = []
    budget = clip_duration_s * MAX_COVERAGE

    for prev, nxt in zip(segs, segs[1:]):
        if len(cues) >= max_cues:
            break
        gap_start = float(getattr(prev, "end", 0.0) or 0.0)
        gap_end = float(getattr(nxt, "start", 0.0) or 0.0)
        if gap_start < HOOK_PROTECT_S:
            continue                      # never cover the hook
        if gap_end - gap_start < min_gap_s:
            continue                      # no real pause here
        dur = min(insert_s, max(MIN_INSERT_S,
                                clip_duration_s - gap_start - 0.5))
        if dur < MIN_INSERT_S:
            continue
        if sum(c.duration_s for c in cues) + dur > budget:
            break

        # The subject comes from the sentence the insert FOLLOWS — it
        # illustrates what was just said, which is what b-roll is for.
        words = keywords(str(getattr(prev, "text", "") or ""), limit=3)
        if not words:
            continue
        subject = " ".join(words[:2])
        prompt = f"{subject}. {style}".strip().rstrip(".") + "."
        cues.append(BRollCue(round(gap_start, 2), round(dur, 2),
                             subject, prompt))

    log.info("broll.planned", cues=len(cues),
             coverage=round(sum(c.duration_s for c in cues)
                            / max(clip_duration_s, 1e-6), 3))
    return cues


def coverage(cues: list[BRollCue], clip_duration_s: float) -> float:
    if clip_duration_s <= 0:
        return 0.0
    return sum(c.duration_s for c in cues) / clip_duration_s


def render_broll(clip: Path, cues: list[BRollCue], *, router, width: int,
                 height: int, work_dir: Path, aspect: str = "9:16",
                 timeout_s: float = 1800.0) -> Path:
    """Generate each cue's insert and composite them over ``clip``.

    Returns the ORIGINAL path when nothing usable was produced. That is
    deliberate: b-roll is a garnish, and a clip that already passed QA
    must not be lost because a generation failed. Every drop is logged, so
    "no b-roll" is never silent.

    Inserts are generated one at a time and each is checked before use —
    a blank generation composited over a good clip is strictly worse than
    no b-roll at all, which is the whole lesson of this codebase.
    """
    import subprocess

    from clipforge.errors import ClipForgeError
    from clipforge.ffmpeg import require_binary

    clip = Path(clip)
    if not cues:
        return clip
    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)

    usable: list[tuple[BRollCue, Path]] = []
    # This walks the cues itself rather than going through
    # `generate_sequence`, so it also owns the shutdown that method does
    # in its `finally`: a provider may hold a worker process and a GPU
    # session between shots, and b-roll is the one caller that would
    # otherwise leave one running after the last cue.
    try:
        for i, cue in enumerate(cues):
            dest = work_dir / f"broll_{i:02d}.mp4"
            try:
                router.generate_shot(prompt=cue.prompt,
                                     seconds=cue.duration_s, fps=24,
                                     out_path=dest, aspect_ratio=aspect)
            except Exception as exc:  # noqa: BLE001
                log.warning("broll.shot_failed", cue=i, subject=cue.subject,
                            error=f"{type(exc).__name__}: {exc}"[:200])
                continue
            if not dest.is_file() or dest.stat().st_size < 1024:
                log.warning("broll.shot_empty", cue=i)
                continue
            usable.append((cue, dest))
    finally:
        close = getattr(router, "close_providers", None)
        if close is not None:
            close()

    if not usable:
        log.warning("broll.none_usable", planned=len(cues),
                    note="shipping the clip without b-roll")
        return clip

    chain = overlay_filter([c for c, _ in usable], width=width, height=height)
    out = clip.with_name(clip.stem + ".broll" + clip.suffix)
    partial = out.with_suffix(out.suffix + ".partial")
    cmd = [str(require_binary("ffmpeg")), "-nostdin", "-hide_banner", "-y",
           "-i", str(clip)]
    for _cue, path in usable:
        cmd += ["-i", str(path)]
    cmd += ["-filter_complex", chain, "-map", "[vout]", "-map", "0:a?",
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-c:a", "copy", "-pix_fmt", "yuv420p", "-f", "mp4", str(partial)]
    proc = subprocess.run(cmd, capture_output=True, text=True,
                          errors="replace", timeout=timeout_s)
    if proc.returncode != 0 or not partial.exists():
        partial.unlink(missing_ok=True)
        log.error("broll.composite_failed",
                  error=(proc.stderr or "")[-300:],
                  note="shipping the clip without b-roll")
        return clip
    partial.replace(out)
    log.info("broll.composited", path=str(out), inserts=len(usable))
    return out


def overlay_filter(cues: list[BRollCue], *, width: int, height: int) -> str:
    """filter_complex that cuts b-roll over the main video at each cue.

    Video only — the speaker's AUDIO continues underneath, which is the
    entire point of b-roll. Replacing the audio too would just be a
    different clip.
    """
    if not cues:
        return ""
    parts, last = [], "[0:v]"
    for i, cue in enumerate(cues):
        src = f"[{i + 1}:v]"
        parts.append(
            f"{src}scale={width}:{height}:force_original_aspect_ratio=increase,"
            f"crop={width}:{height},setsar=1,setpts=PTS-STARTPTS[b{i}]")
        out = f"[v{i}]"
        parts.append(
            f"{last}[b{i}]overlay=enable='between(t,{cue.start_s:.2f},"
            f"{cue.end_s:.2f})'{out}")
        last = out
    return ";".join(parts) + f";{last}null[vout]"
