# Generated by `bta autostart install`. Safe to delete.
Set-Location 'D:\clipforge'
$bta = 'D:\clipforge\.venv\Scripts\bta.exe'
$log = Join-Path 'D:\clipforge' 'workspace\logs\watch_autostart.log'
$botlog = Join-Path 'D:\clipforge' 'workspace\logs\bot_autostart.log'

function Ensure-Bot {
    # The phone's way in: /clip, /status, /retry. Its own process, so a
    # crash in one is not a crash in the other, and restarted from here
    # rather than by a second scheduled task nobody would remember.
    $running = Get-CimInstance Win32_Process -Filter "Name='bta.exe'" |
        Where-Object { $_.CommandLine -like '* bot*' }
    if (-not $running) {
        "$(Get-Date -Format s) starting bta bot" | Out-File -Append -Encoding utf8 $botlog
        Start-Process -FilePath $bta -ArgumentList 'bot' -WindowStyle Hidden -WorkingDirectory 'D:\clipforge' -RedirectStandardOutput $botlog -RedirectStandardError "$botlog.err"
    }
}

while ($true) {
    Ensure-Bot
    "$(Get-Date -Format s) starting bta watch" | Out-File -Append -Encoding utf8 $log
    & $bta watch *>> $log
    "$(Get-Date -Format s) bta watch exited with $LASTEXITCODE" | Out-File -Append -Encoding utf8 $log
    Start-Sleep -Seconds 60
}
