# Generated by `bta autostart install`. Safe to delete.
Set-Location 'D:\clipforge'
$log = Join-Path 'D:\clipforge' 'workspace\logs\watch_autostart.log'
while ($true) {
    "$(Get-Date -Format s) starting bta watch" | Out-File -Append -Encoding utf8 $log
    & 'D:\clipforge\.venv\Scripts\bta.exe' watch *>> $log
    "$(Get-Date -Format s) bta watch exited with $LASTEXITCODE" | Out-File -Append -Encoding utf8 $log
    Start-Sleep -Seconds 60
}
